service: default
runtime: java11
instance_class: F1
automatic_scaling:
  max_instances: 1
entrypoint: java -Xmx128m -jar leif-0.1.0-jar-with-dependencies.jar
handlers:
  - url: /.*
    secure: always
    script: auto
