name: build
on:
  - push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install server dependencies
        run: ./mvnw clean install -DskipTests
      - name: Install client dependencies
        run: npm ci
      - name: Run server tests
        run: ./mvnw clean test
      - name: Run client tests
        run: npm test
