name: build
on:
  - push
env:
  COMPOSER_HOME: ~/.composer
  PHP_VERSION: 7.4
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: "Install PHP version: ${{ env.PHP_VERSION }}"
        run: |
          sudo update-alternatives --set php /usr/bin/php${PHP_VERSION}
          sudo update-alternatives --set phar /usr/bin/phar${PHP_VERSION}
          sudo update-alternatives --set phpdbg /usr/bin/phpdbg${PHP_VERSION}
          sudo update-alternatives --set php-cgi /usr/bin/php-cgi${PHP_VERSION}
          sudo update-alternatives --set phar.phar /usr/bin/phar.phar${PHP_VERSION}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache PHP dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          path: ${{ env.COMPOSER_HOME }}
      - name: Cache Node dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          path: ~/.npm
      - name: Install PHP dependencies
        run: composer install
      - name: Install Node dependencies
        run: npm install
      - name: Server tests
        run: composer run test
      - name: Client tests
        run: npm test
